# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47cb83ccc8f373010c7c06d7b04331ad248896fae6d23cf723c196a6769097a2147419e8d786c31989747f9ed5e1f05602567f04daf244316efe6d490964bf98

test:
  secret_key_base: 12c48e39a5838a235b2bd7828f84f41c59affa2bd0fc378d8d1d875f4b7509c24fb1e7fc58de854166c475a485928b5458e3be7d1b93712e71112cf78b7fc357

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
